Fixed a logic order

diff --git a/host-config b/host-config
--- a/host-config
+++ b/host-config
@@ -3,14 +3,18 @@ set -e
 
 SCRIPT_DIR="$( cd "$( dirname "$0" )" && pwd )"
 CONTAINER_NAME=${CONTAINER_NAME:-$1}
-CONTAINER_ID=`/bin/docker inspect -f {{.Id}} ${CONTAINER_NAME}`
 LAN_INTERFACE=eth0
 VLAN_INTERFACE=eth0m
 CONTAINER_INTERFACE=eth1
 
 # Exit with error if required environment is not present
+if [ -z "${CONTAINER_NAME}" ]; then
+  echo "Envrionment variable CONTAINER_NAME must be provided"
+  exit 1
+fi
+CONTAINER_ID=`/bin/docker inspect -f {{.Id}} ${CONTAINER_NAME}`
 if [ -z "${CONTAINER_ID}" ]; then
-  echo "Envrionment variable CONTAINER_ID must be provided"
+  echo "Could not find CONTAINER_ID from provided CONTAINER_NAME"
   exit 1
 fi
 if [ -z "${HOST_IP_SUBNET}" ]; then
